services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: gridx-mqtt
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data

  redis:
    image: redis:7-alpine
    container_name: gridx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mosquitto_data:
  redis_data: